import 'package:flutter/material.dart';
import 'package:app/Theme/theme-colors.dart';

class PrivacyPolicyPage extends StatelessWidget {
  PrivacyPolicyPage({super.key});

  final String eligibilityTitle = '1. Eligibility';
  final String registrationTitle = '2. Registration';
  final String refundTitle = '3. Refund of Fee';
  final String customerCareTitle = '4. Customer Care';
  final String communicationTitle = '5. Medium of Communication';
  final String trademarkTitle = '6. Trademark';
  final String otherTermsTitle = '7. Other Terms of Use for Members';
  final String membershipTitle = '9. Membership';
  final String disputesTitle = '10. Disputes Between Members';
  final String termsContent = 'WITH EFFECT FROM 1st JUNE 2024 app Jodi  helps you Promote And Advertise your Profile. The Document is an Electronic Record in terms of the Information Technology Act 2000 And Rules they’re under pertaining to electronic Records as applicable and amended. This Electronic Record is generated By a Computer System And does not Require Any Physical or digital Signatures.The appJodi App Has Been Developed, Promoted And Maintained By app Jodi Matrimony. In order to use the appJodi App , you must Register as a member of the app and agree to be bound by these terms of use (Agreement). The Agreement sets out the legally binding terms for your membership.  By choosing to Register you Accept our Terms And Conditions';


  // Section Contents
  final String eligibilityContent = '''
app Jodi Matrimony shall act on the basis of the information that may be submitted by you, believing the same to be true and accurate even if the information is provided during registration by your family, friends, or relatives on your behalf under your express consent. app Jodi Matrimony is under no obligation to verify the accuracy or genuineness of the information submitted by you.

A. The minimum age for registering in app Jodi Matrimony is 18 years for women and 21 years for men.
B. Your use of this site represents and warrants that you have the right, authority, and legal capability to enter into this Agreement and to abide by all of the terms and conditions of this Agreement. You are not prohibited by any law in force from entering into a contract.
C. You have gone through the Terms and Conditions and agree to be bound by them.
D. app Jodi Matrimony reserves the right to terminate your membership or delete your profile without any notice and refund, in case you have made any misrepresentation about your eligibility or have committed any illegal activities through the use of our App.''';

  final String registrationContent = '''
Once you sign up and create an account, you provide us with your login credentials as well as some basic details necessary for the product to work, like your gender and date of birth. By choosing to provide this information, you consent to share the data for our processing purposes. We assure your data is saved with us for one year. This information is solely used by us to provide you with improved matches based on your preferences. Your personal details are always safe with us. You can choose to delete your profile anytime by deleting your account from our App.

You may also call our customer care to assist you in getting your profile registered on our App.
Registration of duplicate profiles of the same person is not allowed on our App. app Jodi shall have full right to suspend or terminate such duplicate profiles without any notice.''';

  final String refundContent = '''
If you choose to terminate your membership, the membership fees are not refundable under any circumstances. Your membership for app Jodi services is for your personal use. You may not authorize others to use your membership, and you may not assign or transfer your account to any other person or entity. The payments made by app Jodi members are treated as non-refundable under any condition.''';

  final String customerCareContent = '''
If you need any help from our customer care, please feel free to contact us:
Email ID: info@app.in
Contact No: 9911388469
Address: 1/4, 1st Floor, East Patel Nagar, Delhi, 110008''';

  final String communicationContent = '''
app Jodi member hereby consents to receiving communication through any medium, such as electronic mails, calls, SMS, or WhatsApp messages from app Jodi. If at any time you want to discontinue receiving these communications, you can write to app Jodi. app Jodi, through its automatic system, sends member profiles via mail, messages, and links. The app Jodi member confirms that the mobile number submitted is not registered with the Do Not Disturb/National Customer Preference Register, and they shall not initiate any complaint.''';

  final String trademarkContent = '''
The trademark indicated on our App belongs to app Jodi Matrimony. app Jodi owns and retains all proprietary rights in the appJodi.in site. The site contains copyrighted material, trademarks, and other proprietary information, service names, and trade addresses that belong to app Jodi. This should not be used in connection with any product or service. You cannot copy, modify, use, publish, or sell any site design, images, in any format''';

  final String otherTermsContent = '''
A. app Jodi Disclaims All Warranties. You expressly agree that your use of this site is at your own risk. app Jodi Matrimony does not assure that the registered users will be able to find their match of interest. app Jodi is only a platform to help you search for your partner. We do not offer guaranteed matchmaking services.

B. app Jodi does not take responsibility for the originality or authenticity of the documents provided by the registered users. app Jodi does not verify credentials of any registered user such as family status, education qualifications, financial status, occupation, phone number, email ID, etc. Members are requested to be careful while shortlisting the profiles and satisfy themselves before making a choice of your match through adequate efforts.

C. You will not post or transmit any content or information that is vulgar, abusive, defamatory, obscene, sexually oriented, illegal, or in violation of the rights of any person. app Jodi Matrimony reserves the right to modify your profile if any prohibitive or objectionable content is found or in case your contact details are being entered in irrelevant fields. app Jodi Matrimony is not responsible for any misuse of your data or your documents. In case of any information or data loss related to registered users on our site due to any reason, app Jodi Matrimony will not be responsible for data information recovery.''';

  final String membershipContent = '''
Membership and rights of admission is reserved only for
A Indian nationals and citizens
B Persons of Indian origin
C Indians Settled Abroad
D Persons of Indian Descent''';

  final String disputesContent = '''
app Jodi registered users are themselves responsible for communication with each other.
app Jodi is not responsible for any kind of dispute between app Jodi members.''';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: pinkColor,
        leading: IconButton(
          icon: Icon(Icons.arrow_back_rounded, color: Colors.white),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        centerTitle: true,
        title: Text(
          'Privacy Policy',
          style: TextStyle(
            fontWeight: FontWeight.w500,
            color: whiteColor,
          ),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(
                24.0), // Adds padding for better readability
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSection("", termsContent),
                _buildSection(eligibilityTitle, eligibilityContent),
                _buildSection(registrationTitle, registrationContent),
                _buildSection(refundTitle, refundContent),
                _buildSection(customerCareTitle, customerCareContent),
                _buildSection(communicationTitle, communicationContent),
                _buildSection(trademarkTitle, trademarkContent),
                _buildSection(otherTermsTitle, otherTermsContent),
                _buildSection(membershipTitle, membershipContent),
                _buildSection(disputesTitle, disputesContent),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 18,
            ),
          ),
          SizedBox(height: 8),
          Text(
            content,
            style: TextStyle(
              fontSize: 16,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
