name: Build Flutter iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'
          channel: stable
          cache: true

      - name: Check Flutter and Xcode
        run: |
          flutter --version
          flutter doctor -v
          xcodebuild -version

      - name: Find Flutter Project
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)

          if [ -z "$PUBSPEC_PATH" ]; then
            echo "ERROR: pubspec.yaml not found!"
            exit 1
          fi

          TARGET_DIR=$(dirname "$PUBSPEC_PATH")

          echo "Flutter project found at: $TARGET_DIR"
          echo "PROJECT_DIR=$TARGET_DIR" >> $GITHUB_ENV

      - name: Flutter Pub Get
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get

      - name: Install CocoaPods
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cd build/ios/iphoneos

          mkdir -p Payload

          cp -R Runner.app Payload/Runner.app

          zip -r ios-app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: aonejodi-ios
          path: ${{ env.PROJECT_DIR }}/build/ios/iphoneos/ios-app.ipa
